name: Update version and Publish Package

on:
  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'Release Type'
        required: true
        default: 'warning'
        type: choice
        options:
        - Major
        - Feature
        - Bug

jobs:
  update-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: 'Set release type : ${{ inputs.ReleaseType }}'
        id: release_type
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ inputs.ReleaseType }}

      - name: Get Latest version from package.json
        id: get_latest_version
        run: |
          # Get the latest version from package.json
          LATEST_VERSION=$(node -p "require('./package.json').version")

          # Output the latest version as a workflow variable
          echo "::set-output name=latest_version::$LATEST_VERSION"

      - name: Extract Current Branch
        id: get_current_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: PreValidation
        id: PreValidation
        run: |
         BRANCH="${{ steps.get_current_branch.outputs.branch }}"
          if [ "$BRANCH" == 'main' ]
            then
              echo "Branch validation Successful"
            else
              echo "Releases only taken from main branch"
              exit 1
          fi

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: ${{ steps.get_latest_version.outputs.latest_version }}
          version-fragment: ${{ steps.release_type.outputs.lowercase }}

      - name: Push latest release tag [v.${{ steps.bump_version.outputs.next-version }}]
  # echo "Release type ${{ inputs.ReleaseType }}" >> $GITHUB_STEP_SUMMARY
  # echo :rocket: v.${{ steps.bump_version.outputs.next-version }} >> $GITHUB_STEP_SUMMARY
        run: |
          npm version ${{ steps.bump_version.outputs.next-version }} --no-git-tag-version
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json

          git commit -m "Bump version to $NEW_VERSION"
          git push origin HEAD:main

          git tag v${{ steps.bump_version.outputs.next-version }}
          git push origin v${{ steps.bump_version.outputs.next-version }}

      # - name: Bump package version and publish package
      #   uses: anothrNick/github-tag-action@v1.55.0
      #   with:
      #     github_token: ${{ secrets.PAT_FOR_TESTING_DEPLOYMENT_REPO }}
      #     tag: true
      #     push_tag: true
      #     tag_prefix: "v"
      #     bump: "minor"
      #     path: "package.json"
      #     commit: true
      #     push: true
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
